"""Synthetic AP214 assemblies used by the tests.

The fixtures deliberately reproduce the awkward parts of real exports: complex
instances, multi-line records, comments, semicolons inside strings, several
records on one physical line and a solid that is only reachable through a
backward SHAPE_REPRESENTATION_RELATIONSHIP.
"""

from __future__ import annotations

from pathlib import Path

HEADER = """ISO-10303-21;
HEADER;
/* Generated for tests; contains a semicolon and an apostrophe: don't */
FILE_DESCRIPTION(('test assembly'),'2;1');
FILE_NAME('ROOT_ASM','2026-01-01T00:00:00',(''),(''),'test','test','');
FILE_SCHEMA(('AUTOMOTIVE_DESIGN { 1 0 10303 214 1 1 1 1 }'));
ENDSEC;
DATA;
"""

BODY = """#1=APPLICATION_CONTEXT('automotive_design');
#2=APPLICATION_PROTOCOL_DEFINITION('international standard','automotive_design',
2001,#1);
#3=PRODUCT_CONTEXT('',#1,'mechanical');#4=PRODUCT_DEFINITION_CONTEXT(
'part definition',#1,'design');
#10=PRODUCT('ROOT_ASM','ROOT_ASM','a name with a ; and an '' apostrophe',(#3));
#11=PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE('','',#10,.NOT_KNOWN.);
#12=PRODUCT_DEFINITION('design','',#11,#4);
#13=PRODUCT_DEFINITION_SHAPE('','shape of ROOT_ASM',#12);

#20=PRODUCT('SUB_ASM','SUB_ASM','',(#3));
#21=PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE('','',#20,.NOT_KNOWN.);
#22=PRODUCT_DEFINITION('design','',#21,#4);
#23=PRODUCT_DEFINITION_SHAPE('','shape of SUB_ASM',#22);

#30=PRODUCT('LEAF_PART','LEAF_PART','',(#3));
#31=PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE('','',#30,.NOT_KNOWN.);
#32=PRODUCT_DEFINITION('design','',#31,#4);
#33=PRODUCT_DEFINITION_SHAPE('','shape of LEAF_PART',#32);

#40=PRODUCT('OTHER_PART','OTHER_PART','',(#3));
#41=PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE('','',#40,.NOT_KNOWN.);
#42=PRODUCT_DEFINITION('design','',#41,#4);
#43=PRODUCT_DEFINITION_SHAPE('','shape of OTHER_PART',#42);

#50=NEXT_ASSEMBLY_USAGE_OCCURRENCE('1','Next assembly relationship',
'SUB_ASM',#12,#22,$);
#51=NEXT_ASSEMBLY_USAGE_OCCURRENCE('2','Next assembly relationship',
'LEAF_PART',#22,#32,$);
#52=NEXT_ASSEMBLY_USAGE_OCCURRENCE('3','Next assembly relationship',
'OTHER_PART',#12,#42,$);

#60=(NAMED_UNIT(*)LENGTH_UNIT()SI_UNIT(.MILLI.,.METRE.));
#61=(NAMED_UNIT(*)PLANE_ANGLE_UNIT()SI_UNIT($,.RADIAN.));
#62=(NAMED_UNIT(*)SOLID_ANGLE_UNIT()SI_UNIT($,.STERADIAN.));
#63=UNCERTAINTY_MEASURE_WITH_UNIT(LENGTH_MEASURE(1.E-6),#60,'accuracy','tol');
#64=(GEOMETRIC_REPRESENTATION_CONTEXT(3)GLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT((#63))
GLOBAL_UNIT_ASSIGNED_CONTEXT((#60,#61,#62))REPRESENTATION_CONTEXT('','3D'));

#70=CARTESIAN_POINT('',(0.E0,0.E0,0.E0));
#71=DIRECTION('',(0.E0,0.E0,1.E0));
#72=DIRECTION('',(1.E0,0.E0,0.E0));
#73=AXIS2_PLACEMENT_3D('',#70,#71,#72);

#80=SHAPE_REPRESENTATION('',(#73),#64);
#81=SHAPE_DEFINITION_REPRESENTATION(#13,#80);
#82=SHAPE_REPRESENTATION('',(#73),#64);
#83=SHAPE_DEFINITION_REPRESENTATION(#23,#82);
#84=SHAPE_REPRESENTATION('',(#73),#64);
#85=SHAPE_DEFINITION_REPRESENTATION(#33,#84);
#86=SHAPE_REPRESENTATION('',(#73),#64);
#87=SHAPE_DEFINITION_REPRESENTATION(#43,#86);

/* The solid of LEAF_PART is only reachable backwards, like Creo writes it. */
#90=CARTESIAN_POINT('',(1.E0,2.E0,3.E0));
#91=VERTEX_POINT('',#90);
#92=MANIFOLD_SOLID_BREP('leaf solid',#91);
#93=ADVANCED_BREP_SHAPE_REPRESENTATION('',(#92,#73),#64);
#94=SHAPE_REPRESENTATION_RELATIONSHIP('','',#84,#93);

#95=CARTESIAN_POINT('',(9.E0,9.E0,9.E0));
#96=VERTEX_POINT('',#95);
#97=MANIFOLD_SOLID_BREP('other solid',#96);
#98=ADVANCED_BREP_SHAPE_REPRESENTATION('',(#97,#73),#64);
#99=SHAPE_REPRESENTATION_RELATIONSHIP('','',#86,#98);

#100=PRODUCT_DEFINITION_SHAPE('Placement #1','placement of SUB_ASM',#50);
#101=ITEM_DEFINED_TRANSFORMATION('','',#73,#73);
#102=(REPRESENTATION_RELATIONSHIP('','',#82,#80)
REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION(#101)
SHAPE_REPRESENTATION_RELATIONSHIP());
#103=CONTEXT_DEPENDENT_SHAPE_REPRESENTATION(#102,#100);

#110=PRODUCT_DEFINITION_SHAPE('Placement #2','placement of LEAF_PART',#51);
#111=ITEM_DEFINED_TRANSFORMATION('','',#73,#73);
#112=(REPRESENTATION_RELATIONSHIP('','',#84,#82)
REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION(#111)
SHAPE_REPRESENTATION_RELATIONSHIP());
#113=CONTEXT_DEPENDENT_SHAPE_REPRESENTATION(#112,#110);

#120=PRODUCT_DEFINITION_SHAPE('Placement #3','placement of OTHER_PART',#52);
#121=ITEM_DEFINED_TRANSFORMATION('','',#73,#73);
#122=(REPRESENTATION_RELATIONSHIP('','',#86,#80)
REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION(#121)
SHAPE_REPRESENTATION_RELATIONSHIP());
#123=CONTEXT_DEPENDENT_SHAPE_REPRESENTATION(#122,#120);

#130=COLOUR_RGB('',1.E0,0.E0,0.E0);
#131=FILL_AREA_STYLE_COLOUR('',#130);
#132=FILL_AREA_STYLE('',(#131));
#133=SURFACE_STYLE_FILL_AREA(#132);
#134=SURFACE_SIDE_STYLE('',(#133));
#135=SURFACE_STYLE_USAGE(.BOTH.,#134);
#136=PRESENTATION_STYLE_ASSIGNMENT((#135));
#137=STYLED_ITEM('',(#136),#92);
#138=STYLED_ITEM('',(#136),#97);
#139=MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION('',(#137,#138),#64);

#140=PRODUCT_RELATED_PRODUCT_CATEGORY('part','',(#10,#20,#30,#40));
#141=PROPERTY_DEFINITION('material','',#32);
#142=DESCRIPTIVE_REPRESENTATION_ITEM('MATERIAL','steel');
#143=REPRESENTATION('',(#142),#64);
#144=PROPERTY_DEFINITION_REPRESENTATION(#141,#143);
ENDSEC;
END-ISO-10303-21;
"""


def write_assembly(path: Path) -> Path:
    path.write_text(HEADER + BODY, encoding="latin-1")
    return path
